/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#1e0f13",
        "surface-2": "#161619",
        "primary-container": "#ff4a8e",
        "inverse-on-surface": "#3e2b30",
        "surface-container-high": "#372529",
        "inverse-primary": "#ba005c",
        "surface-bright": "#483439",
        "on-primary-container": "#590028",
        error: "#FF3333",
        "secondary-fixed-dim": "#c8c6c7",
        "tertiary-container": "#19a72f",
        "on-primary-fixed": "#3f001b",
        primary: "#ffb1c5",
        secondary: "#c8c6c7",
        "text-subtle": "#94949E",
        "pink-muted": "#A31D56",
        "on-secondary-container": "#bab8b9",
        success: "#00FFCC",
        "on-background": "#fadbe1",
        "primary-fixed-dim": "#ffb1c5",
        "on-error-container": "#ffdad6",
        "surface-dim": "#1e0f13",
        "on-tertiary-fixed": "#002203",
        "surface-1": "#111113",
        "text-muted": "#4E4E54",
        "surface-container-lowest": "#190a0e",
        "surface-tint": "#ffb1c5",
        "on-surface-variant": "#e3bdc5",
        "primary-fixed": "#ffd9e1",
        "tertiary-fixed-dim": "#5fe060",
        "on-secondary-fixed": "#1c1b1c",
        "surface-container-highest": "#433034",
        tertiary: "#5fe060",
        "on-surface": "#fadbe1",
        "surface-variant": "#433034",
        "on-primary": "#65002f",
        background: "#1e0f13",
        "outline-variant": "#5b3f46",
        "on-secondary-fixed-variant": "#474647",
        "inverse-surface": "#fadbe1",
        "on-tertiary-fixed-variant": "#00530f",
        outline: "#aa888f",
        "surface-container-low": "#27171b",
        "on-primary-fixed-variant": "#8f0045",
        warning: "#FFAA00",
        "secondary-container": "#4a494a",
        "secondary-fixed": "#e5e2e3",
        "tertiary-fixed": "#7cfe79",
        "error-container": "#93000a",
        "pink-neon": "#FF007F",
        "surface-container": "#2c1b1f",
        "on-error": "#690005",
        "pink-glow": "rgba(255, 0, 127, 0.12)",
        "on-tertiary-container": "#003206",
        "on-tertiary": "#003908",
        "on-secondary": "#313031",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "gutter-desktop": "24px",
        "margin-desktop": "32px",
        "max-width": "1200px",
        "gutter-mobile": "16px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "display-md": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "display-lg": ["Space Grotesk", "sans-serif"],
      },
      fontSize: {
        "display-md": ["2.5rem", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-lg": ["1.5rem", { lineHeight: "1.4", fontWeight: "600" }],
        "label-mono": ["0.75rem", { lineHeight: "1", fontWeight: "500" }],
        "body-sm": ["0.875rem", { lineHeight: "1.5", fontWeight: "400" }],
        "body-md": ["1rem", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg-mobile": ["1.25rem", { lineHeight: "1.4", fontWeight: "600" }],
        "display-lg": ["3.5rem", { lineHeight: "1.1", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
}
