export const MOCK_OPPORTUNITIES = [
  {
    id: 1,
    pair: "ETH/USDC",
    dexA: "Uniswap",
    dexB: "PancakeSwap",
    priceA: 1802.40,
    priceB: 1817.20,
    diff: 0.82,
    profit: 12.40,
    gas: 3.20,
    slippage: 0.5,
    status: "pending",
  },
  {
    id: 2,
    pair: "SOL/USDC",
    dexA: "Raydium",
    dexB: "Orca",
    priceA: 142.15,
    priceB: 143.91,
    diff: 1.24,
    profit: 24.80,
    gas: 0.15,
    slippage: 0.3,
    status: "pending",
  },
  {
    id: 3,
    pair: "AVAX/USDT",
    dexA: "Trader Joe",
    dexB: "Uniswap",
    priceA: 35.42,
    priceB: 35.75,
    diff: 0.93,
    profit: 15.10,
    gas: 1.80,
    slippage: 0.5,
    status: "expired",
  },
  {
    id: 4,
    pair: "MATIC/USDC",
    dexA: "QuickSwap",
    dexB: "Uniswap",
    priceA: 0.721,
    priceB: 0.728,
    diff: 0.97,
    profit: 8.40,
    gas: 2.10,
    slippage: 0.4,
    status: "pending",
  },
  {
    id: 5,
    pair: "LINK/ETH",
    dexA: "Uniswap",
    dexB: "PancakeSwap",
    priceA: 0.00845,
    priceB: 0.00852,
    diff: 0.83,
    profit: 6.20,
    gas: 3.50,
    slippage: 0.6,
    status: "executed",
  },
]

export const MOCK_HISTORY = [
  {
    id: 3,
    pair: "AVAX/USDT",
    dexA: "Trader Joe",
    dexB: "Uniswap",
    diff: 0.93,
    profit: 15.10,
    status: "expired",
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 5,
    pair: "LINK/ETH",
    dexA: "Uniswap",
    dexB: "PancakeSwap",
    diff: 0.83,
    profit: 6.20,
    status: "executed",
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
]

export const SIMULATION_RESULT = {
  grossProfit: 24.80,
  gasFee: 0.15,
  dexFee: 1.24,
  slippageCost: 0.43,
  netProfit: 22.98,
  roi: 1.15,
}
